---
- hosts: master
  tasks:
  - name: Install Containerized ETCD
    command: docker run -d -v /certs:/etc/ssl/certs -p 4001:4001 -p 2380:2380 -p 2379:2379 --name etcd quay.io/coreos/etcd:v2.3.8 -name etcd0 -advertise-client-urls http://172.20.10.2:2379,http://172.20.10.2:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls http://172.20.10.2:2380 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster-1 -initial-cluster etcd0=http://172.20.10.2:2380 -initial-cluster-state new
    become: true
