---
- hosts: master
  tasks:
  - name: Install registry docker v2 in https
    command: $ docker run --net=host -d --name=kube-apiserver --restart=always -v /certs:/etc/ssl/certs k8s.gcr.io/hyperkube:v1.9.9 kube-apiserver --etcd-servers=http://172.20.10.2:2379 --service-cluster-ip-range=10.0.0.1/24 --insecure-port=8080 --secure-port=6443
    become: true

